### ISSUE TITLE
Every Title an Error

### ISSUE THREAD

**Issue by beefsquatch523** [Prince25/Titles-To-IMDB-IDs#1]
Hi,
Great tool here that I've used in the past, but now query seems to never make a top pick and only gives an options page that outputs as an error. Did IMDb change something about how they handle queries or is there just a new site to point at maybe? It'd be awesome if this tool could work again. For info I gave it a 300+ title txt file to process and every title came back as an error.
Thanks, Jer

**Comment by Prince25** [comment]
Thanks for letting me know. IMDB started denying HTML fetching without a user agent and changed their page structure. Fixed in  826842639adfd149b36a7648472ebcf39339628a.

Try it out.

**Comment by beefsquatch523** [comment]
Works like a charm again! Thanks so much. Good work!
