### ISSUE TITLE
Error on All Titles

### ISSUE THREAD

**Issue by SpacePirate87** [Prince25/Titles-To-IMDB-IDs#2]
Using a custom list and the example.txt, keep getting the following error: 'Cannot read property 'includes' of undefined'

I've tried on Windows and Linux, both are giving the same error.

**Comment by Prince25** [comment]
Thanks for letting me know. It should be fixed in 32f077db251e1361bcac38a57236fd7df6f85b35.

**Comment by SpacePirate87** [comment]
Works now, thank you!
